[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "quent"
version = "1.9.0"
authors = [{ name = "Ohad Drukman", email = "drukmano@icloud.com" }]
description = "Yet Another Chain Interface."
license = { file = "LICENSE" }
readme = "README.md"
requires-python = ">=3.7"
keywords = ['chain', 'chaining', 'cascade', 'fluent', 'pipe', 'piping', 'interface', 'syntax', 'async']
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Intended Audience :: Developers",
    "Programming Language :: Python",
    "Programming Language :: Cython",
    "Operating System :: OS Independent",
    "Topic :: Software Development",
    "Topic :: Software Development :: Libraries :: Python Modules",
]

[project.urls]
homepage = "https://github.com/drukmano/quent.git"
